"""Fix quiz_id to UUID

Revision ID: 4e72da6d72e2
Revises: e15e39fd9be7
Create Date: 2025-06-18 19:02:28.242667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e72da6d72e2'
down_revision: Union[str, None] = 'e15e39fd9be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=False, server_default='mcq'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
